jobs:
  build:
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - run: go version
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...